x-common-env: &common_env
  TZ: Asia/Jakarta

services:
  # Milvus Standalone (resmi)
  milvus:
    image: milvusdb/milvus:v2.5.11
    container_name: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      COMMON_RUN_MODE: standalone
      ETCD_USE_EMBED: "true"
      MINIO_USE_EMBED: "true"
      MQ_TYPE: rocksmq
      COMMON_ENABLE_JEMALLOC: "false"
    # ⬇️ Pastikan ADA command ini (agar CMD tidak kosong)
    command: ["milvus", "run", "standalone"]
    volumes:
      - milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 5s
      timeout: 3s
      retries: 30

  # Qdrant (resmi)
  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: qdrant
    profiles: ["qdrant"]
    environment:
      <<: *common_env
    ports: ["6333:6333", "6334:6334"]
    volumes:
      - qdrant_data:/qdrant/storage

  # Weaviate (resmi)
  weaviate:
    image: semitechnologies/weaviate:1.31.0
    container_name: weaviate
    profiles: ["weaviate"]
    environment:
      <<: *common_env
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      CLUSTER_HOSTNAME: "node1"
      QUERY_DEFAULTS_LIMIT: "10"
      ENABLE_MODULES: "" # tanp a modul agar ringan
    ports: ["8080:8080"]
    volumes:
      - weaviate_data:/var/lib/weaviate

  # Benchmark runner (Python 3.13)
  bench:
    build: ./bench
    container_name: bench
    profiles: ["bench"]
    stdin_open: true
    tty: true
    environment:
      <<: *common_env
      DATA_ROOT: /datasets
    volumes:
      - ./bench:/app
      - ./datasets:/datasets
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["sleep", "infinity"]

  # (Opsional) fio baseline
  fio:
    image: alpine:3.20
    container_name: fio
    profiles: ["fio"]
    entrypoint:
      ["/bin/sh", "-lc", "apk add --no-cache fio && tail -f /dev/null"]
    volumes:
      - milvus_data:/target # kamu bisa tes juga weaviate_data/qdrant_data

volumes:
  milvus_data:
  qdrant_data:
  weaviate_data:
